### PR TITLE
Handle lifespan events correctly

### PR DESCRIPTION
**Pull request by logileifs**
Currently this middleware eats up application lifespan events so startup and shutdown handlers don't work, this fixes that

### CODE REVIEW

**Review by acidjunk — COMMENTED** [review]
hmm, this breaks the test.

Not sure if the test is wrong. I know that the current tests could use some love and more asserts.
Can you fix the tests?

If not: NP I will have look at this after my holidays

**Comment by logileifs** [comment]
Was there a particular reason you didn't use `BaseHTTPMiddleware` for the tracing?
I've been trying out this code and it seems to work as expected without having to deal with the lifespan events:

```from urllib.parse import urlunparse

import opentracing
from opentracing.ext import tags
from opentracing import InvalidCarrierException
from opentracing import SpanContextCorruptedException
from starlette.middleware.base import BaseHTTPMiddleware


class TracingMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, tracer):
        super().__init__(app)
        self._tracer = tracer

    async def dispatch(self, request, call_next):
        span_ctx = None
        headers = {}
        for k, v in request.headers.items():
            headers[k.lower().encode("utf-8")] = v.encode("utf-8")

        try:
            span_ctx = self._tracer.extract(
                opentracing.Format.HTTP_HEADERS,
                headers
            )
        except (InvalidCarrierException, SpanContextCorruptedException):
            pass

        scope = request.scope
        with self._tracer.start_active_span(
            str(scope["path"]), child_of=span_ctx, finish_on_close=True
        ) as tracing_scope:
            span = tracing_scope.span
            span.set_tag(tags.COMPONENT, "asgi")
            span.set_tag(tags.SPAN_KIND, tags.SPAN_KIND_RPC_SERVER)
            span.set_tag(tags.HTTP_METHOD, scope["method"])
            host, port = scope["server"]
            url = urlunparse(
                (str(scope["scheme"]), f"{host}:{port}", str(scope["path"]), "", str(scope["query_string"]), "",)
            )
            span.set_tag(tags.HTTP_URL, url)

            response = await call_next(request)
        return response
```

**Comment by acidjunk** [comment]
No rational reason for the middleware choice: initial work was influenced by something I found in FastAPI forum: and I'm still quite new to Starlette/FastAPI.

Looks better/simpler by using starlette middleware. Will test it in our stack early next week (still on holiday).

**Review by acidjunk — APPROVED** [review]
Merging; will do some afterwork on tests

**Comment by acidjunk** [comment]
@logileifs : I took the liberty to rewrite the middleware so it's based on Starlette's BaseHTTPMiddleware. It was already a todo in the code.

Had to remove the UTF8 encoding as that seems to be handled by the Starlette middleware itself.
When I've some time in the coming weeks I will try to increase the test coverage a bit.

**Pull request merged**
